version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: workload-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workload_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

# volumes:
#   postgres-data:
